spring:
  application:
    name: CONFIG-DEFAULT

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL for service registration and discovery
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
